/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'didier.franco' at '7/03/17 02:07 PM' with Gradle 2.14.1
 *
 * @author didier.franco, @date 7/03/17 02:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
